### ISSUE TITLE
引入含有java9后module新特性的依赖导致报错

### ISSUE THREAD

**Issue by nfzsh** [lipangeng/Java-Dependence-Analysis#1]
引入log4j-api-2.14.1.jar包时，由于打包时使用了module新特性导致在log4j-api-2.14.1.jar!\META-INF\versions\9module-info.class会引起报错
Exception in thread "main" java.lang.RuntimeException: cannot find META-INF.versions.9.module-info: module-info found in META-INF/versions/9/module-info.class
        at javassist.CtClassType.getClassFile3(CtClassType.java:226)
        at javassist.CtClassType.makeFieldCache(CtClassType.java:983)
        at javassist.CtClassType.getMembers(CtClassType.java:974)
        at javassist.CtClassType.getDeclaredFields(CtClassType.java:1073)
        at cn.lipg.instrument.jda.InstrumentChecker.clazz(InstrumentChecker.java:177)
        at cn.lipg.instrument.jda.JdaApplication.main(JdaApplication.java:51)

**Comment by nfzsh** [comment]
已提pr，应该是使用相关新特性的依赖应用都会出现此问题，Java8下直接排除应该是无影响
